# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pickled_optparse}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Bethany"]
  s.date = %q{2010-11-02}
  s.description = %q{Adds the ability to easily specify and test for required switches in Ruby's built-in OptionParser class}
  s.email = %q{picklepumpers@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "HISTORY.rdoc",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "autotest/discover.rb",
    "examples/example.rb",
    "lib/pickled_optparse.rb",
    "lib/pickled_optparse/pickled_optparse.rb",
    "lib/pickled_optparse/version.rb",
    "spec/pickled_optparse/pickled_optparse_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/PicklePumpers/pickled_optparse}
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new("~> 1.9.2")
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Adds required switches to Ruby's OptionParser class}
  s.test_files = [
    "examples/example.rb",
    "spec/pickled_optparse/pickled_optparse_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.1"])
      s.add_development_dependency(%q<syntax>, [">= 1.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.1"])
      s.add_dependency(%q<syntax>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.1"])
    s.add_dependency(%q<syntax>, [">= 1.0.0"])
  end
end

